name: branch

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env: { CODE_VERSION: 'stable', DISPLAY: ':99.0', GHC: 9.4.5 }
    steps:
    - uses: actions/checkout@v3

    - name: Set up npm
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Set up GHC ${{ env.GHC }} environment
      run: |
        echo "resolver: ghc-${{ env.GHC }}" > stack.yaml
        echo "packages: []" >> stack.yaml
        stack setup
  
    - run: npm install

    - name: Run tests
      uses: smithki/xvfb-action@v1.1.2
      with:
        run: npm run test

    - name: Add GHC extension output (on failure)
      if: failure()
      run: find .vscode-test/udd/logs -name *GHC* -exec cat {} \;
